[package]
name = "my-gtk-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.5.1", package = "gtk4" }
once_cell = "1.16.0"

[build-dependencies]
glib-build-tools = "0.16.0"